### ISSUE TITLE
Модель сети Петри

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox-models#10]
Сети Петри раньше использовались для описания и моделирования дискретных параллельных, асинхронных систем. 

Разработать модель сети Петри, описывающей функционирование гибкой производственной ячейки, состоящей из двух станков, одного робота и накопителей. Функционирование ячейки моделируется изменениями в маркировке сети Петри.

Для 2 человек.

**Comment by NikBandurist** [comment]
Команда: Бандурист, Гринкина

**Comment by aurusov** [comment]
>Команда: Бандурист, Гринкина

Видел и в работе и на защите только одного разработчика - Татьяну.

**Comment by NikBandurist** [comment]
Да, добрый день!

Все верно, Бандурист анимацию не завершил. Соответственно допбалл ставьте
одной Гринкиной.

15 декабря 2016 г., 10:16 пользователь Andrey Urusov <
notifications@github.com> написал:
