### ISSUE TITLE
Модель работы порта

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox-models#11]
Моделируется морской нефтеналивной порт, который обслуживает танкеры трех типов. Танкеры каждого типа прибывают в порт по случайным законам, различным для каждого типа. Танкеры прибывают на рейд, затем в порядке приоритетов перемещаются единственным буксиром к причалам для заливки нефтью. Время буксировки одинаковое для всех танкеров. Время заливки нефтью для танкеров различного типа различное и случайное. После заливки нефтью танкер с помощью того же буксира покидает порт. Причалов в порту три. В этом районе моря периодически возникает шторм во время которого буксировка танкеров запрещена.

Задача: Определить загрузку причалов, загрузку буксира, потери от простоев танкеров в ожидании буксировки. Оценить к чему приведет обслуживание дополнительных танкеров четвертого типа и принять решение обслуживать их или нет.

Для 2-3 человек.

**Comment by melkikh** [comment]
Команда:
Мелких Саша, анимация
Матроницкий Леша, логика, результаты

**Comment by Matronitskiy** [comment]
Андрей Витальевич, ссылка на наш репозиторий: https://github.com/Matronitskiy/Model_port
файл - port_v9.rao
На данном этапе готова полная модель порта, но пока без анимации.

**Comment by aurusov** [comment]
Отлично. У меня есть замечания, но чтобы их было удобно обсуждать на гитхабе, прошу сделать следующее
- форкнуть к себе текущую репу (https://github.com/aurusov/raox-models)
- добавить свою модель прямо в корень, назвать её с маленькой буквы `model_port`
- залить не только `*.rao` и все необходимые файлы для импорта в `raox-eclipse` (список файлов можно посмотреть тут https://github.com/aurusov/raox-models/tree/master/models/barber_activity)
- потом поставить пул-реквест на эту репу и начнется веселье

**Comment by aurusov** [comment]
Что-то я подумал, а зачем в названии модели иметь слово `model`. Масло-масленое. Прошу переименовать в `seaport`. Но сделайте это в тот момент, когда никаких локальных изменений не будет, когда все залито на гитхаб. Если возникнут проблемы с гитом или со сборкой, то готов сделать сам после занятий.

**Comment by aurusov** [comment]
Алексей, вам Саша передал про дискриминационный бонус (или тройка автоматом или билет на экзамене, но бонус сгорает) и про то, что в след. субботу можно пересдать модель и получить нормальный бонус ?

**Comment by aurusov** [comment]
@Matronitskiy 
Алексей, вам Саша передал про дискриминационный бонус (или тройка автоматом или билет на экзамене, но бонус сгорает) и про то, что в след. субботу можно пересдать модель и получить нормальный бонус ?

**Comment by Matronitskiy** [comment]
@aurusov Андрей Витальевич, да передал, спасибо!
