### ISSUE TITLE
Модель почтового отделения связи

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox-models#12]
Объектом моделирования служит типовое почтовое отделение. Отделение реализует процесс обслуживания клиентов и дальнейшую обработку их заявок. Клиенты обслуживаются в операционных окнах почтового отделения, после чего производится дополнительная обработка каждой заявки.

Обслуживание может быть организовано различными способами, отличающимися числом операционных окон, услугами (типами заявок), закрепленными за окнами, длительностью рабочего дня, организацией работы окон (операторов) внутри рабочего дня, временем обработки заявок клиентов, интенсивностью входного потока клиентов и т.п.

Задача:
- Собрать загрузку парикмахеров
- Собрать статистику по времени нахождения клиентов в очереди, кол-ву клиентов в очереди, времени обслуживания и времени нахождения в системе
- Рассчитать пропускную способность системы
- Оценить изменение этих параметров при внедрении новых услуг

Для 3-х человек.

**Comment by AlexandraSmirnova** [comment]
Выполняют: Смирнова Александра(РК9-17), Ануфриева Екатерина(РК9-18)
