### ISSUE TITLE
Модель сервисной службы

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox-models#18]
В сервисной службе присутствуют следующие должности:
- Сервисный инженер 8 человек
- Менеджер по подбору запасных частей 3 человека
- Курьер для доставки запасных частей 2 человека
  В сервисную службу поступают заявки на ремонт оборудования. Часть  заявок  требует  установки запасных частей. Подбор осуществляет менеджер. Некоторый  процент  запасных  частей  является заказным и доставляется курьером.

Необходимо  выявить  самое  узкое  место при работе сервисной службы.

Для 2-3 человек.

**Comment by nikolayantoncev** [comment]
Антонцев Н.М. РК9-18

**Comment by nikolayantoncev** [comment]
@aurusov Андрей Витальевич, добавил код в репозиторий, надеюсь все так. Хотелось бы узнать об анимации и исправлениях. https://github.com/nikolayantoncev/Customer_servise.git

**Comment by aurusov** [comment]
Бегло пробежал, все хорошо. Ближайшие планы
- Готовлю новый релиз. После его выхода, попрошу залить не только текст модели.
- Задачу необходимо наполнить реальными данными. Вам необходимо пообщаться с Андреем Мирошниковым, контакты которого скину вам на почту. Не нашел вашей почты, напиши мне письмо.

**Comment by aurusov** [comment]
Проделайте действия, аналогичные https://github.com/aurusov/raox-models/issues/11#issuecomment-257015570. Назовите модель `service department`.

**Comment by aurusov** [comment]
Насколько я понимаю, на задачу вы забили ? Если нет, то срочно выходите на связь.

**Comment by aurusov** [comment]
Делает Храмов Андрей.
