### ISSUE TITLE
Модель работы котла

### ISSUE THREAD

**Issue by andreyvatanin** [aurusov/raox-models#23]
![default](https://cloud.githubusercontent.com/assets/18644989/19909757/2054ba80-a09a-11e6-9278-ec43581f6799.png)

Газ - желтая линия; вода - синяя линия; воздух - голубая линия.

### Задача
Смоделировать работу котельной в трех режимах:
1. Штатный режим работы котла;
2. Критическое давление газа на вводе к котлу;
3. Пожар в котельной.

### Особенности
- Реализовать возможность выбирать разный период опроса системы;
- Единица модельного времени 1 секунда;
- Ограничение: при работе модели температура на улице должна быть [ -70 ; 10 ] градусов.
- Зависимости температуры выхода воды (прямой воды) и мощности газовой горелки от температуры на улице определены в таблице 1 ниже:
![image](https://cloud.githubusercontent.com/assets/18644989/19944316/5d0e1338-a14c-11e6-9c18-764f756b9921.png)

### Описание котла
- Котел нагревает воду для отопления зала котельной и потребительских помещений;
- Температура входа воды в котел (обратной воды) должна стремиться и не может быть больше  70 градусов (по заданию);
- Если температура входа воды (обратной воды) ниже 40 градусов, то включается насос, он выключается при температуре 50 градусов. Насос помогает быстрее нагревать воду, если она имеет низкую температуру;
- Температура выхода воды из котла (прямой воды) зависит от температуры на улице. Зависимость представлена формулой на основании таблицы 1:  **= (10 - Т.улицы) / 3.33 + 91**.

### Описание газовой горелки
- К газовой горелке обеспечен вход газа и воздуха;
- Мощность газовой горелки влияет на температуру выхода воды из котла  (прямой воды), поэтому мощность зависит от температуры на улице. Зависимость представлена формулой на основании таблицы 1: **= 30 - Т.улицы**.

### Особенности
- Каждый день в 12:00 горячая вода спускается на охлаждение стоков и в сеть поступает холодная вода в течении часа. К 13:00 температура входа воды (обратной воды) опускается примерно до 20 градусов.

### Описание режима критического давления
- Отключаются все системы
- Открывается клапан для вывода газа в атмосферу
- Что делать с системой после **В РАЗРАБОТКЕ**

### Особенности режима критического давления
- Созданием условий для реализации режима критического давления газа на вводе к котлу является неисправность регулятора давления газа, что приводит к постепенному увеличению давления газа на вводе к котлу.

### Описание режима пожар
- Отключаются все системы
- Что делать с системой после **В РАЗРАБОТКЕ**

### Особенности режима пожар
- Созданием условий для реализации режима пожар является создание регулярного события.

**Comment by andreyvatanin** [comment]
@aurusov Посмотрите, пожалуйста, описание и прокомментируйте.

Вместо вопросов (**??? № ???**) нужно что-то написать. Хочется увидеть Ваше мнение. Мое такое:

??? 1 ???)
Пожар активировать по заданному изначально условию времени или что-то похожее на это.

??? 2 ???)
1 Вариант. После появления критического давления завершать работу модели.
2 Вариант. Через единицу модельного времени (секунда) сбрасывать давление с критического уровня до оптимального и продолжать работу системы.
3 Вариант. Запускать систему спустя, например, час. Но тогда требует место обсуждение параметров системы при запуске. Потому что температура на улице должна изменяться этот час, вода по идее остывать и т.д.. Это усложнит систему, надо ли?

??? 3 ???)
Аналогично вопросу выше ??? 2 ???.

**Comment by aurusov** [comment]
Первое впечатление - отличное описание. Давай уберем двоеточие у заголовков. Еще немного переформулировал задачу

---

### Задача

Смоделировать работу котельной в трех режимах:
1. Штатный режим работы котла (почему котельной, а не помещения, которое где-то там слева ?)
2. Критическое давление газа на вводе к котлу
3. Пожар в котельной

---
1. `Котел нагревает воду для отопления зала котельной` - почему зала котельной, а не помещения, которое где-то там слева ? Хочется перестать обогревать котельную - звучит странно. Котельная нужна, чтобы обогревать жилое/рабочее помещение или целое здание. Разве не так ?
2. `Температура входа воды в котел должна стремиться и не может быть больше 70 градусов (по заданию).` - почему входа, а не выхода ? И сама формулировка взрывает мозг, попробуй написать проще, как-то так `Температура нагретой котлом воды должна стремиться...` Или я неправильно понял про что тут ?
3. `Зависимость представлена формулой: = (10 - Т.улицы) / 3.33 + 91.` - надо раскрыть магические константы
4. Условия критического давления и пожара надо перенести в соответствующие режимы
5. `??? 1 ???` - `В режим пожара система переходит по регулярному событию или по нажатию на соответствующий элемент анимации.`
6. `??? 2 ???` - я за третий вариант. Изменение температуры на улице и воды и так должны быть запилены для штатного режима. Т.е. они не увеличивают сложность модели в этом месте.
7. `??? 3 ???` - тоже подождать какое-то время (время устранения пожара, может быть пседво-случайной величиной, от 1 часа до 2 дней, к примеру) и продолжить работу. Температура на улице и связанная с ней температура в помещении должна моделироваться независимо от этого. Температура в трубах во время простоя опускается до минимума.

**Comment by andreyvatanin** [comment]
1. `Котел нагревает воду для отопления зала котельной - почему зала котельной, а не помещения, которое где-то там слева ? Хочется перестать обогревать котельную - звучит странно. Котельная нужна, чтобы обогревать жилое/рабочее помещение или целое здание. Разве не так ?`
   Напишу как есть и исправлю в описании. В реальности котел нагревает воду, которая используется для отопления котельного зала (котельной) и потребительских помещений (которые где-то там слева).  И отопление самого зала котельной обязательно, там стоят котлы, а для них важно поддерживать заданную температуру в помещении.
2. `Температура входа воды в котел должна стремиться и не может быть больше 70 градусов (по заданию). - почему входа, а не выхода ? И сама формулировка взрывает мозг, попробуй написать проще, как-то так Температура нагретой котлом воды должна стремиться... Или я неправильно понял про что тут ?`
   Вода выхода или прямая вода - выходит из котла , а вода входа или обратная вода - входит в котел. Если говорят, что котел нагревает воду до 105 градусов, то имеется в виду температура прямой воды. Температура обратной воды - это температура воды, которая прошла цикл и вот-вот подходит снова к котлу.
   Есть в России стандарт на котельные и на температуру воды, как теплоносителя. Согласно этому стандарту температура не может быть ниже какого-то значения, потому что там могут завестись бактерии и тд и тп. Поэтому, наверное, все городские котельные работают с графиком температур 105/70 (105 - температура прямой воды, 70 - обратной). В данной модели мы управляем температурой прямой воды в зависимости от температуры окружающей среды, чего не делают городские котельные.
3. `Зависимость представлена формулой: = (10 - Т.улицы) / 3.33 + 91. - надо раскрыть магические константы`
   Формулы зависимости температуры выхода воды (прямой воды) и мощности газовой горелки от температуры на улице взяты на основании таблице ниже
   ![image](https://cloud.githubusercontent.com/assets/18644989/19943724/ba193c40-a149-11e6-8a5a-87a7353525bf.png)
4. `Условия критического давления и пожара надо перенести в соответствующие режимы`
   Сделано.
5. `??? 1 ??? - В режим пожара система переходит по регулярному событию или по нажатию на соответствующий элемент анимации.`
   Хорошо.

7 - 8. `??? 2 ??? - я за третий вариант. Изменение температуры на улице и воды и так должны быть запилены для штатного режима. Т.е. они не увеличивают сложность модели в этом месте.`
 `??? 3 ??? - тоже подождать какое-то время (время устранения пожара, может быть пседво-случайной величиной, от 1 часа до 2 дней, к примеру) и продолжить работу. Температура на улице и связанная с ней температура в помещении должна моделироваться независимо от этого. Температура в трубах во время простоя опускается до минимума.`
В разработке.

**Comment by aurusov** [comment]
1. Модель рассчитана на использование студентами и др. неподготовленными людьми. Нужно как можно проще описать задачу. Понятно, что помещение, где стоит котел, тоже должно обогреваться.
2. Спасибо за пояснения. Т.е. ниже 70-ти градусов нельзя из-за бактерий ? Не очень понимаю, если дальше вода нагревается до 105 и только потом поступает потребителям. К тому же они её не пьют. Получается, бактерии могут повредить входящие трубы ?
3. Во, это другое дело. Погрешность небольшая, будем использовать формулу. Но надо обязательно к постанове задачи прикрепить эту таблицу, а из исходника сделать комментарий со ссылкой на неё

**Comment by aurusov** [comment]
Прошу разобраться с примером
https://github.com/aurusov/acceleration/blob/master/main.cpp

**Comment by andreyvatanin** [comment]
![image](https://cloud.githubusercontent.com/assets/18644989/20950225/74d6c50c-bc2f-11e6-91e9-3569d4e3430b.png)
Газ - желтая линия; вода - синяя линия; воздух - голубая линия.

## Постановка задачи
Смоделировать работу котельной в трех режимах:
1. Режим растопки котла;
2. Режим штатной работы котла;
3. Режим пожара в котельной.

Особенности:
- Возможность выбирать разный период опроса системы;
- Единица модельного времени - 1 [с];
- График зависимости температуры прямой и обратной воды от температуры на улице представлен ниже:
![image](https://cloud.githubusercontent.com/assets/18644989/20951178/57f5fbf0-bc35-11e6-871c-e2d39243631b.png)
Выведены соответствующие формулы:
Температура_прямой_воды = 59.28 - 0.99 * Температура_на_улице;
Температура_обратной_воды = 45.04 - 0.54 * Температура_на_улице.

В расчетах используется формула W * t = c * m * ΔТ, где
W - текущая мощность горелки;
t - время, в рамках модели t = 1 [с];
с - удельная теплоемкость воды, с = 4200 [Дж/(кг*°С)];
m - масса нагреваемой воды в котле m = 10 [кг/сек];
ΔТ - разница температур прямой и обратной воды перед котлом [°С].

## Режим растопки котла
По эксплуатационным характеристикам в режиме растопки на котел накладываются следующие ограничения:
- Скорость нагрева прямой воды должна быть ограничена 30 [°С/час];
- Температура обратной воды должна быть желательно не меньше 40 [°С], поэтому для увеличения температуры воды перед котлом используется насос.
- При достижении расчетной температуры прямой воды котел переходит в режим штатной работы

## Режим штатной работы котла
- Насос выключен. 
По эксплуатационным характеристикам в штатном режиме работы на котел накладываются следующие ограничения:
- Максимальная температура прямой воды - 115 [°С];
- Максимальная разность температур прямой и обратной воды - 40 [°С];
- Максимальная мощность котла - 1680 [кВт];
- Максимальная скорость изменения мощности котла - 10 [кВт/с];

## Режим пожара в котельной
### Описание
- Наступление пожара осуществляется с помощью кнопки "Активизировать пожар";
- Отключаются все системы, открывается клапан вывода газа в атмосферу;
- Время ликвидации пожара случайная величина от 1 до 2 часов.

**Comment by andreyvatanin** [comment]
Убрал из задачи режим критического давления газа на вводе к котлу. Этот режим по алгоритму и прочему похож на режим пожара, поэтому не стал на этом этапе его добавлять. Если надо, сделаю.

Время ликвидации пожара, согласен, сделал маленькое, в силу единицы модельного времени равной одной секунде. Но если его делать день-два, то очень тяжело работать, по крайне мере на моем ноуте. Эклипс зависает через раз.

Про визуализацию помню, что Вам не нравится. Как с моделью все будет хорошо, займусь этим.
